### ISSUE TITLE
Cannot figure out how to run the program

### ISSUE THREAD

**Issue by VaylenObscuras** [krogenth/G2DataGUI#11]
Tried running the program, but I don't find an .exe or something anywhere. Help?

**Comment by krogenth** [comment]
Hey Vaylen, you can find the latest release version here:
https://github.com/krogenth/G2DataGUI/releases/download/0.0.9b/G2DataGUI.exe

Otherwise, you can download the codebase, and install Visual Studio Community:
https://visualstudio.microsoft.com/vs/community/
then open the `G2DataGUI.sln` file in `./vs/` and compile to generate the `.exe`.

**Comment by VaylenObscuras** [comment]
Thanks a bunch, this seems to work now. Looks pretty easy to edit, actually. Thanks for your work ^.^

**Comment by krogenth** [comment]
Excellent, glad it's all sorted out now. Closing this issue, but feel free to open another with any other troubles you run into.

**Comment by krogenth** [comment]
No, you will need to restart the game in order for changes to take effect unfortunately. But you can keep the program open when you do play, so you can make adjustments as you play. However, making adjustments to things like starting stats will require you to start a new game.
